// Generates src/app/data/embedded-assets.ts from the files in public/.
// The game assets are embedded as data URLs / inline JSON so the widget
// works when served from file:// (e.g. on a Samsung Tizen TV), where
// fetch() to file:// URLs is blocked.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = join(root, 'public');
const levelsDir = join(publicDir, 'levels');
const outFile = join(root, 'src', 'app', 'data', 'embedded-assets.ts');

const images = ['tiles.png', 'hero.png', 'enemies.png'];

const imageEntries = images.map((name) => {
  const data = readFileSync(join(publicDir, name));
  const key = name.replace(/\.png$/, '');
  return `  ${key}: 'data:image/png;base64,${data.toString('base64')}',`;
});

const levelFiles = readdirSync(levelsDir)
  .filter((f) => f.endsWith('.json'))
  .sort();

const levelEntries = levelFiles.map((f) => {
  const key = f.replace(/\.json$/, '');
  const json = readFileSync(join(levelsDir, f), 'utf8');
  return `  '${key}': ${json},`;
});

const content = `// AUTO-GENERATED by scripts/embed-assets.mjs - do not edit manually.
// Run \`npm run embed:assets\` to regenerate.
export const embeddedAssets: {
  tiles: string;
  hero: string;
  enemies: string;
  levels: Record<string, unknown>;
} = {
${imageEntries.join('\n')}
  levels: {
${levelEntries.join('\n')}
  },
};
`;

writeFileSync(outFile, content);
console.log(`Wrote ${outFile} (${content.length} bytes)`);
